# Generated by Django 3.0.5 on 2023-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20230216_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('grams', (('250 grams', '250'), ('500 grams', '500'))), ('kg', (('1kg', '1'),))], max_length=50, null=True),
        ),
    ]
